run-name: checkout
name: checkout_wf

on: 
    push: 

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: list files
              run: ls